# Generated by Django 3.2.3 on 2021-05-16 22:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='Authors name')),
                ('last_name', models.CharField(max_length=100, verbose_name='Authors surname')),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Book title')),
                ('genre', models.CharField(choices=[('action_adventure', 'Action and Adventure'), ('detective', 'Detective'), ('fantasy', 'Fantasy'), ('hist_fic', 'Historical Fiction'), ('horror', 'Horror'), ('romance', 'Romance'), ('sci_fi', 'Sci-Fi')], help_text='Select a genre for this book', max_length=20)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.author', verbose_name='Author of the book')),
            ],
        ),
    ]
